export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_LANE';
export const DELETE_ARTICLE = 'ARTICLE';
export const ARTICLES_REFRESHED = 'ARTICLES_REFRESHED';

export const SWITCH_MODE = 'SWITCH_MODE';

export const EDITING = 'EDITING';
export const PREVIEW = 'PREVIEW';

export const AUTHENTICATED = 'AUTHENTICATED';
export const LOGGED_OUT = 'LOGGED_OUT';

export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
